### PR TITLE
Add the possibility to have it's own key bindings in config file

### PR DESCRIPTION
**Pull request by rpesche**
Some work need to be done

- [ ] Check multiple binding of one key
- [ ] Change help message to print user keybindings
- [ ] Add documentation to see all possible keybinding

I will do it in the next days

### CODE REVIEW

**Comment by AnthonyDiGirolamo** [comment]
Nice work @rpesche the only error I can see is that the toggle-border function isn't working. Could you apply this fix?

```
diff --git a/todotxt_machine/urwid_ui.py b/todotxt_machine/urwid_ui.py
index 9b77a2e..f7bdf57 100644
--- a/todotxt_machine/urwid_ui.py
+++ b/todotxt_machine/urwid_ui.py
@@ -494,7 +494,7 @@ class UrwidUI:
             self.clear_filters()
         elif self.key_bindings.is_binded_to(input, 'toggle-wrapping'):
             self.toggle_wrapping()
-        elif self.key_bindings.is_binded_to(input, 'toggle-toolbar'):
+        elif self.key_bindings.is_binded_to(input, 'toggle-borders'):
             self.toggle_border()
         elif self.key_bindings.is_binded_to(input, 'toggle-sorting'):
             self.toggle_sorting()
```

Do you want to finish implementing those changes you mention before merging?

**Comment by AnthonyDiGirolamo** [comment]
I just merged in pull request #18 that adds a couple more key bindings in edit mode. Could you add in those as well?

**Comment by AnthonyDiGirolamo** [comment]
Thanks very much for your work! I've been meaning to add this support for a long time.

**Comment by rpesche** [comment]
Thank for your response.

I think you can merge this.
The remained tasks are just here for more comfort.

(I did commit your fix about 'toggle-border' mistake

**Comment by AnthonyDiGirolamo** [comment]
Hey @rpesche I got this merged and added a `--show-default-bindings` option that can be appended to the config file. Also made the in app help show currently configured bindings. If you can give it a try and let me know what you think.

**Pull request merged**
