### PR TITLE
pep8 + Flake8 fixes

### PR DESCRIPTION
**Pull request by nicwest**
ref #35 

Also cleaned up some legacy stuff

### CODE REVIEW

**Comment by simonvanderveldt** [comment]
@AnthonyDiGirolamo are you still using and working on todotxt-machine? Any chance the open PRs can be incorporated?

**Comment by AnthonyDiGirolamo** [comment]
Sorry for the massive delay! Happy to merge this in. Looks like I merged things out of order and it now has conflicts. If you can't resolve I'll just lint the existing code.

**Comment by nicwest** [comment]
no problemo

**Comment by AnthonyDiGirolamo** [comment]
Thanks very much!

**Pull request merged**
