### PR TITLE
Added support for a few more useful keyboard shortcuts in edit mode

### PR DESCRIPTION
**Pull request by khughitt**
- `cntl + u`  Delete form cursor to beginning of line
- `cntl + left` Navigate one word left
-  `cntl + right` Navigate one word right

Thanks for all of your work on todotxt-machine. I am loving it :)

### CODE REVIEW

**Comment by AnthonyDiGirolamo** [comment]
Thanks for adding this @khughitt! Now that we have a pull request for custom key bindings I'm finally getting around to this.

**Comment by rpesche** [comment]
I'm confused.
I thought that we already has the code to go one word left/right with the default keys "ctrl-f" and "ctrl-b".
What is the difference between these two ?

**Comment by AnthonyDiGirolamo** [comment]
You're right @rpesche, and with your custom bindings feature it should be easy for users to modify it.

**Comment by khughitt** [comment]
If another PR adds better keyboard shortcut support, go ahead and merge that. My main goals were to add some bash-like support for navigating and editing entries.

**Comment by AnthonyDiGirolamo** [comment]
Hey @khughitt I kept the delete to beginning of line key since that was missing. I've merged #27 and updated its functionality so you can add `ctrl-left` and `ctrl-right` to the ` ~/.todotxt-machinerc` by adding it to the keys section:

```
[keys]
edit-word-left = meta b, ctrl b, ctrl left
edit-word-right = meta f, ctrl f, ctrl right
```

Run `todotxt-machine --show-default-bindings` to see all the default bindings. Let me know if that works for you.

**Pull request merged**
